---
- name: Update database servers
  hosts: dbserver
  become: yes

  tasks:
  - name: Ensure mysql-server is at the latest version
    ansible.builtin.apt:
      name: mysql-server
      state: present

  - name: start and enable mysql
    ansible.builtin.service:
      name: mysql
      state: started
      enabled: yes

  - name: install python mysql
    ansible.builtin.apt:
      name: python3-mysqldb
      state: present


  - name: Create a new database with name 'dbadmin'
    mysql_db:
      name: dbadmin
      state: present

  - name: Create a new database user with name 'dbuser'
    mysql_user:
      name: dbuser
      password: admin123
      priv: '*.*:ALL'
      state: present
